// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPBu2uexB3j8NOUsQMQYJYz1VkBeHdpLc',
    appId: '1:846209530009:web:52d281ce8c752fbb8aa008',
    messagingSenderId: '846209530009',
    projectId: 'appointmentapp-1f7a9',
    authDomain: 'appointmentapp-1f7a9.firebaseapp.com',
    storageBucket: 'appointmentapp-1f7a9.appspot.com',
    measurementId: 'G-8HKBJCMY5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI5v_SxypKdrBdqpoQPPppDub5b4OAbgM',
    appId: '1:846209530009:android:4193674ccbdef9d98aa008',
    messagingSenderId: '846209530009',
    projectId: 'appointmentapp-1f7a9',
    storageBucket: 'appointmentapp-1f7a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAnQ03fSyY_YsVmJSRzhs8hf8JwIsQ7YU',
    appId: '1:846209530009:ios:4c0f2d4bf4fdb96a8aa008',
    messagingSenderId: '846209530009',
    projectId: 'appointmentapp-1f7a9',
    storageBucket: 'appointmentapp-1f7a9.appspot.com',
    iosBundleId: 'com.example.appointmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAnQ03fSyY_YsVmJSRzhs8hf8JwIsQ7YU',
    appId: '1:846209530009:ios:b532ad9da4e7c3478aa008',
    messagingSenderId: '846209530009',
    projectId: 'appointmentapp-1f7a9',
    storageBucket: 'appointmentapp-1f7a9.appspot.com',
    iosBundleId: 'com.example.appointmentApp.RunnerTests',
  );
}
